# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 06:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='視聴日')),
                ('track_id', models.CharField(blank=True, max_length=20, verbose_name='トラックID')),
                ('itunes_url', models.URLField(blank=True, verbose_name='iTunesStore URL')),
                ('preview_url', models.URLField(blank=True, verbose_name='プレビューURL')),
                ('img_url30', models.URLField(blank=True, verbose_name='Height30画像URL')),
                ('img_url60', models.URLField(blank=True, verbose_name='Height60画像URL')),
                ('img_url100', models.URLField(blank=True, verbose_name='Height100画像URL')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('director', models.CharField(blank=True, max_length=20, verbose_name='監督')),
                ('genre', models.CharField(blank=True, max_length=10, verbose_name='ジャンル')),
                ('release', models.CharField(blank=True, max_length=4, verbose_name='リリース')),
                ('runtime', models.CharField(blank=True, max_length=10, verbose_name='上映時間')),
                ('score', models.IntegerField(default=3, verbose_name='スコア')),
                ('review', models.TextField(blank=True, verbose_name='レビュー')),
            ],
        ),
    ]
